name: restore npm cache
description: restore npm cache and node_modules

inputs:
  token:
    description: NPM_AUTH_TOKEN
    required: false
    default: ''

outputs:
  npm-cache-hit:
    description: see actions/cache
    value: ${{ steps.restore-cache.outputs.cache-hit }}
  npm-cache-primary-key:
    description: see actions/cache
    value: ${{ steps.restore-cache.outputs.cache-primary-key }}
  npm-cache-matched-key:
    description: see actions/cache
    value: ${{ steps.restore-cache.outputs.cache-matched-key }}
  node_modules-cache-hit:
    description: see actions/cache
    value: ${{ steps.restore-node_modules.outputs.cache-hit }}
  node_modules-cache-primary-key:
    description: see actions/cache
    value: ${{ steps.restore-node_modules.outputs.cache-primary-key }}
  node_modules-cache-matched-key:
    description: see actions/cache
    value: ${{ steps.restore-node_modules.outputs.cache-matched-key }}

runs:
  using: composite
  steps:
    - id: detect-pm
      shell: bash
      run: |
        if [ -f 'pnpm-lock.yaml' ]
        then
          echo 'pm=pnpm' | tee -a "$GITHUB_OUTPUT"
          echo "dir=$(pnpm store path)" | tee -a "$GITHUB_OUTPUT"
        else
          echo 'pm=npm' | tee -a "$GITHUB_OUTPUT"
          echo "dir=$(npm config get cache)" | tee -a "$GITHUB_OUTPUT"
        fi

    - id: os-info
      uses: openameba/action-os-info@b1395f434e5fc0aab838ce4f823d6c844e230f07 # v1.0.0

    - id: cache-key
      shell: bash
      run: >
        echo 'suffix=${{ format('{0}-{1}-{2}-{3}', runner.environment, runner.arch, runner.os, steps.os-info.outputs.version) }}'
        | tee -a "$GITHUB_OUTPUT"

    - id: restore-cache
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ${{ steps.detect-pm.outputs.dir }}
        key: ${{ steps.detect-pm.outputs.pm }}-${{ steps.cache-key.outputs.suffix }}-${{ hashFiles('pnpm-lock.yaml', '**/package-lock.json') }}
        restore-keys: |
          ${{ steps.detect-pm.outputs.pm }}-${{ steps.cache-key.outputs.suffix }}-
          ${{ steps.detect-pm.outputs.pm }}-

    - if: steps.detect-pm.outputs.pm == 'npm'
      id: restore-npm-node_modules
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: '**/node_modules'
        # NOTE: restore node_modules only when key matches exactly
        key: node_modules-${{ steps.cache-key.outputs.suffix }}-${{ hashFiles('**/package-lock.json') }}

    - id: restore-node_modules
      shell: bash
      run: |
        if [ "$PM" == 'npm' ]
        then
          echo "cache-hit=${{ steps.restore-npm-node_modules.outputs.cache-hit }}" | tee -a "$GITHUB_OUTPUT"
          echo "cache-primary-key=${{ steps.restore-npm-node_modules.outputs.cache-primary-key }}" | tee -a "$GITHUB_OUTPUT"
          echo "cache-matched-key=${{ steps.restore-npm-node_modules.outputs.cache-matched-key }}" | tee -a "$GITHUB_OUTPUT"
        else
          echo 'cache-hit=false' | tee -a "$GITHUB_OUTPUT"
          echo 'cache-primary-key=' | tee -a "$GITHUB_OUTPUT"
          echo 'cache-matched-key=' | tee -a "$GITHUB_OUTPUT"
        fi
      env:
        PM: ${{ steps.detect-pm.outputs.pm }}

    - if: steps.detect-pm.outputs.pm == 'pnpm'
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts --prefer-offline
      env:
        NPM_AUTH_TOKEN: ${{ inputs.token }}

    - if: steps.restore-node_modules.outputs.cache-hit != 'true' && steps.detect-pm.outputs.pm == 'npm'
      shell: bash
      run: npm ci --no-audit --ignore-scripts --prefer-offline --no-progress
      env:
        NPM_AUTH_TOKEN: ${{ inputs.token }}

    - shell: bash
      run: >
        "$PM" rebuild && "$PM" run --if-present prepare
      env:
        PM: ${{ steps.detect-pm.outputs.pm }}
